

title: my personal website
email: rajgarg021@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Just getting started, lot more to come
baseurl: "" # the subpath of your site, e.g. /blog
url: "rajgarg021.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rajgarg021
github_username:  rajgarg021

# Build settings
theme: minima
# theme: jekyll-theme-primer

plugins:
  - jekyll-feed